class UserNotFoundException(Exception):
    pass

class UserCreatingException(Exception):
    pass